language: node_js
node_js:
  - 14
before_install:
  - npm install -g codecov
script:
  - npm install
  - npm run build
notifications:
  slack:
    rooms:
      - secure: "jlewoWC2yPWHoVzSEmNwp6Q8UKWc7nAUySv5DCAagEJAXFZlYJo5AkHGB6bvRonNJwbdYH6xwYhs0N4tLe2XQuBO63vT17Va8VKUa+zGBhpslPPLd/8sRz+effMsFzqVco0z1p4DnjK6I7KCzUPS8TWFxaDeDOVYyunNuLuzJ6ZmNWcuTxFYlwXniBEx6mWY2CZDErB0ySnedhc5kkxnWmZCeiUDIzkhTZsE7MDSYO7C7HsxENbvhSkhk9Y9xJaZK/UUJHAeBkCDFZslkB490GlRyHBqkIQceKIxwNbsxDFGcenXRfW9Ggh3xnFB+7kQbM9c+wpTiuAi5LkQXgrK/aIkVVjbwmatFN4RzErK6gWUTrfZXZfqlYkkvQF8qWnOPuZp+zhe+5IK7Rsywo74UMzB6z5pAmYMJW9KpDeAzXYt92As6nqy+OtVPFiCSNPaeXbB6hDT1J03upiDKqdroMb5TE6qNSj+GlljhSPnJ/YAeO3AmQxkLDLk2NbZkjjOvyHoluZaP995pqHcYaKQkwKdjEzHNcESv8WIoJb6aNoD3HyFkRe96jGpk/doHJUE9LvbGSFfp8qW4hqc5CQP4ljP7EidabzaUAlIe8EfD7Lbc+Lag6wgH/g2xkFbL4fM4jolsDcLOK+bD7MJPnHtN+/ANJt+gcJwA/zPVyqnn2c="
      - secure: "OC2tIAisvQ0n+I6X2CDYua4VB8Zby2hrRblzylC03HvOLg+7zuIanmeN6q/SRGIHesZARLStpghK2sknp8bZ9FyGpU6sBLbAQ0bV6pgqaxqnFvbamytmNYRfNkso83cKOse1dYmlQrbum/QuFO1DNO1BMixK9EL5gMdpg8wERUa7vXwBqlrlXYtzNBZ2sKCmT8GBs16t/iZYprYwZXSQq5kXYkT3Xu/WHX6D9c7kFQkRZJAuCOrNSOtXIPye9Y8UkkV7WXX44ToUV7o6+fpbmi2vapz4YGncHgwfcW3vj9nXrRBycbaUxDT4t4XJ8yaUUmwwQjeVJrA0LU8ZQP+Une14RpyGOd8YgajOZLO2o3g0aPlU2adbYJsXvoM4sZtYoWgZ92VtFvN3xPu7KreobdO2C00xC8iJa+HwppjhyqAQEArnX6vX0vJ3EMmk6Y78MSvfBgilRBiXaeyPKVwYQkTKYk879KHD3niylunAUC67NvjgwrBsB8sEl/VwSvLlmPuHmDBeDRePJ3XOeCPo8V+lBvOJSObDNEipVPkZUm1XkJZVJhg5No9YUvUee//71ni1y5MK4T9AZlqAWfr6Jr+ZJFoJ8nid9CY+EIXj4ZDfHWfFPSEOEyI4R7Taq5B9+hMINS4QICFXG4h5LqJksLh0eTQ9DC/lNNsmLg6WVoY="
