language: node_js
node_js:
  - 14
before_install:
  - npm install -g codecov
script:
  - npm install
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
